apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: batelyerushalmiii/hello-world-webapp:ed8f745
          ports:
<<<<<<< HEAD
            - containerPort: 5000 
          readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
=======
            - containerPort: 5000
>>>>>>> c8cf906eb56b7fd94431f354a59b5e0866356989
