name: Build and Deploy

on:
 push:
   branches:
     - main

jobs:
 build:
   name: Build and Push Docker Image
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Extract Git SHA
       id: vars
       run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-webapp:latest
           ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-webapp:${{ env.GIT_SHA }}

 deploy:
   name: Update Deployment
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Configure Git
       run: |
         git config --global user.name 'GitHub Actions Bot'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'

     - name: Update Deployment file
       uses: mikefarah/yq@master
       with:
         cmd: yq '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/hello-world-webapp:${{ env.GIT_SHA }}"' -i k8s/hello-world/deployment.yaml

     - name: Commit and push changes
       run: |
         git add k8s/hello-world/deployment.yaml
         git commit -m "Update image tag to ${{ env.GIT_SHA }}"
         git push origin main