name: 'Application CI/CD'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'k8s/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'k8s/**'

jobs:
  build:
    name: 'Build and Test Application'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # בדיקת תקינות קבצי Kubernetes
    - name: Validate Kubernetes manifests
      uses: azure/k8s-lint@v1
      with:
        manifests: |
          k8s/hello-world/*.yaml

    # בנייה ודחיפה של תמונת Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

  deploy:
    needs: build
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # התחברות ל-AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    # עדכון תצורת kubectl
    - name: Update kube config
      run: aws eks update-kubeconfig --name migdal-eks-cluster --region eu-west-1

    # פריסת האפליקציה
    - name: Deploy application
      run: |
        kubectl apply -f k8s/hello-world/namespace.yaml
        kubectl apply -f k8s/hello-world/deployment.yaml
        kubectl apply -f k8s/hello-world/service.yaml